import {displayName} from '../../app.json';
import {icons} from './icons';

export const isDev = true;
// export const isDev = false;
let domain, socketUrl, S3_URL, appName, websiteBaseUrl;
if (isDev) {
  // domain = "https://apidevfeatures.dynamitelifestyle.com/";
  // socketUrl = "https://apidevfeatures.dynamitelifestyle.com"
  // S3_URL = "https://dd-feature-app-bucket.s3.amazonaws.com/"
  // websiteBaseUrl = "https://galaxy.dynamitelifestyle.com/"
  // appName = displayName;

  domain = 'http://192.168.0.239:4615/v1/auth/';
  // https://apidev.dynamitelifestyle.com/v1/auth/';
  socketUrl = 'https://apidev.dynamitelifestyle.com';
  S3_URL = 'https://dynamite-lifestyle-dev-app-bucket.s3.amazonaws.com/';
  appName = displayName;
  websiteBaseUrl = 'https://sourcedev.dynamitelifestyle.com/';
} else {
  domain = 'https://api.dynamitelifestyle.com/v1/auth/';
  socketUrl = 'https://apicron.dynamitelifestyle.com';
  S3_URL = 'https://dynamite-lifestyle-prod-app-bucket.s3.amazonaws.com/';
  appName = displayName;
  websiteBaseUrl = 'https://source.dynamitelifestyle.com/';
}

const passwordEncryptionKey =
  'lU0WFyJoLnN6FGxyoWap7O13yG6zSJBUKiFdizpfwyixdwf83ClzJMBgJaUCtGIibiC6mY8dmuxwd2xpVoCrooODlTiXBlkoaWeeedLn1O3ebbaDxAZwMXDDc1DOH4aaUjg7I7kYJf4iHMZVlmRvsbtfwvixw6SlAzWAdTnv79EySnNc57uQyjmZfevuPtFrkdozFlTjT51ltOkFE30EwKGPkjWqmPtgqYaE7cEA0Bu0t1UL7Bf7QaIAd3fugvDF';
export const apiKey = 'DynamiteLifestyle@3ZGErMDCyxTOZYFr56HGD';
export {
  domain,
  socketUrl,
  S3_URL,
  appName,
  websiteBaseUrl,
  passwordEncryptionKey,
};

export const S3Urls = [
  'https://dynamite-lifestyle-dev-app-bucket.s3.amazonaws.com/',
  'https://dynamite-lifestyle-prod-app-bucket.s3.amazonaws.com/',
  'https://dd-feature-app-bucket.s3.amazonaws.com/',
];

export const googleScopes = [
  'https://www.googleapis.com/auth/userinfo.email',
  'https://www.googleapis.com/auth/calendar',
  'https://www.googleapis.com/auth/calendar.events',
];

// export const GoogleClientIdsForAndroidDebugMode = "608984481708-77j6lt82sp1jpftfejgb1955l2gheuid.apps.googleusercontent.com";
export const GoogleClientIdsForAndroidDebugMode =
  '608984481708-hlglln5pdb2uiamk352rf3tg2rf3v93n.apps.googleusercontent.com'; //?  Beacuse of package changed

export const communityLevelObj = {
  dynamite: 'Dynamite',
  pta: 'PTA',
  elite: 'Elite',
  mastery: 'VIP Gold',
};

export const communityLevelArr = [
  {
    title: 'Dynamite',
    value: 'dynamite',
  },
  {
    title: 'PTA',
    value: 'pta',
  },
  {
    title: 'Elite',
    value: 'elite',
  },
  {
    title: 'VIP Gold',
    value: 'mastery',
  },
];

export const communityLevelWithAllObj = {
  dynamite: 'Dynamite',
  pta: 'PTA',
  elite: 'Elite',
  mastery: 'VIP Gold',
  all: 'All',
};

export const communityLevelWithAllArr = [
  {
    title: 'All',
    value: 'all',
  },
  {
    title: 'Dynamite',
    value: 'dynamite',
  },
  {
    title: 'PTA',
    value: 'pta',
  },
  {
    title: 'Elite',
    value: 'elite',
  },
  {
    title: 'VIP Gold',
    value: 'mastery',
  },
];

export const dateTimeFormat = {
  date: 'DD-MM-YYYY',
  date2: 'YYYY-MM-DD',
  time: 'hh:mm A',
  dateTime: 'DD-MM-YYYY hh:mm A',
  dateTimeWithText: text => `DD-MM-YYYY [${text}] hh:mm A`,
  conversion: 'YYYY-MM-DD HH:mm:ss',
};

export const PRIORITY_ARR = [
  {
    value: 1,
    color: '#959292',
    title: 'Low',
    icon: () => icons.flag('#959292', 20),
  },
  {
    value: 2,
    color: '#79D34C',
    title: 'Medium',
    icon: () => icons.flag('#79D34C', 20),
  },
  {
    value: 3,
    color: '#F8D748',
    title: 'High',
    icon: () => icons.flag('#F8D748', 20),
  },
  {
    value: 4,
    color: '#EB574C',
    title: 'Critical',
    icon: () => icons.flag('#EB574C', 20),
  },
];

export const PRIORITY_OBJECT = {
  1: {
    value: 1,
    color: '#959292',
    title: 'Low',
  },
  2: {
    value: 2,
    color: '#79D34C',
    title: 'Medium',
  },
  3: {
    value: 3,
    color: '#F8D748',
    title: 'High',
  },
  4: {
    value: 4,
    color: '#EB574C',
    title: 'Critical',
  },
};

export const TimeZones = [
  'Europe/Andorra',
  'Asia/Dubai',
  'Asia/Kabul',
  'Europe/Tirane',
  'Asia/Yerevan',
  'Antarctica/Casey',
  'Antarctica/Davis',
  'Antarctica/DumontDUrville',
  'Antarctica/Mawson',
  'Antarctica/Palmer',
  'Antarctica/Rothera',
  'Antarctica/Syowa',
  'Antarctica/Troll',
  'Antarctica/Vostok',
  'America/Argentina/Buenos_Aires',
  'America/Argentina/Cordoba',
  'America/Argentina/Salta',
  'America/Argentina/Jujuy',
  'America/Argentina/Tucuman',
  'America/Argentina/Catamarca',
  'America/Argentina/La_Rioja',
  'America/Argentina/San_Juan',
  'America/Argentina/Mendoza',
  'America/Argentina/San_Luis',
  'America/Argentina/Rio_Gallegos',
  'America/Argentina/Ushuaia',
  'Pacific/Pago_Pago',
  'Europe/Vienna',
  'Australia/Lord_Howe',
  'Antarctica/Macquarie',
  'Australia/Hobart',
  'Australia/Currie',
  'Australia/Melbourne',
  'Australia/Sydney',
  'Australia/Broken_Hill',
  'Australia/Brisbane',
  'Australia/Lindeman',
  'Australia/Adelaide',
  'Australia/Darwin',
  'Australia/Perth',
  'Australia/Eucla',
  'Asia/Baku',
  'America/Barbados',
  'Asia/Dhaka',
  'Europe/Brussels',
  'Europe/Sofia',
  'Atlantic/Bermuda',
  'Asia/Brunei',
  'America/La_Paz',
  'America/Noronha',
  'America/Belem',
  'America/Fortaleza',
  'America/Recife',
  'America/Araguaina',
  'America/Maceio',
  'America/Bahia',
  'America/Sao_Paulo',
  'America/Campo_Grande',
  'America/Cuiaba',
  'America/Santarem',
  'America/Porto_Velho',
  'America/Boa_Vista',
  'America/Manaus',
  'America/Eirunepe',
  'America/Rio_Branco',
  'America/Nassau',
  'Asia/Thimphu',
  'Europe/Minsk',
  'America/Belize',
  'America/St_Johns',
  'America/Halifax',
  'America/Glace_Bay',
  'America/Moncton',
  'America/Goose_Bay',
  'America/Blanc-Sablon',
  'America/Toronto',
  'America/Nipigon',
  'America/Thunder_Bay',
  'America/Iqaluit',
  'America/Pangnirtung',
  'America/Atikokan',
  'America/Winnipeg',
  'America/Rainy_River',
  'America/Resolute',
  'America/Rankin_Inlet',
  'America/Regina',
  'America/Swift_Current',
  'America/Edmonton',
  'America/Cambridge_Bay',
  'America/Yellowknife',
  'America/Inuvik',
  'America/Creston',
  'America/Dawson_Creek',
  'America/Fort_Nelson',
  'America/Vancouver',
  'America/Whitehorse',
  'America/Dawson',
  'Indian/Cocos',
  'Europe/Zurich',
  'Africa/Abidjan',
  'Pacific/Rarotonga',
  'America/Santiago',
  'America/Punta_Arenas',
  'Pacific/Easter',
  'Asia/Shanghai',
  'Asia/Urumqi',
  'America/Bogota',
  'America/Costa_Rica',
  'America/Havana',
  'Atlantic/Cape_Verde',
  'America/Curacao',
  'Indian/Christmas',
  'Asia/Nicosia',
  'Asia/Famagusta',
  'Europe/Prague',
  'Europe/Berlin',
  'Europe/Copenhagen',
  'America/Santo_Domingo',
  'Africa/Algiers',
  'America/Guayaquil',
  'Pacific/Galapagos',
  'Europe/Tallinn',
  'Africa/Cairo',
  'Africa/El_Aaiun',
  'Europe/Madrid',
  'Africa/Ceuta',
  'Atlantic/Canary',
  'Europe/Helsinki',
  'Pacific/Fiji',
  'Atlantic/Stanley',
  'Pacific/Chuuk',
  'Pacific/Pohnpei',
  'Pacific/Kosrae',
  'Atlantic/Faroe',
  'Europe/Paris',
  'Europe/London',
  'Asia/Tbilisi',
  'America/Cayenne',
  'Africa/Accra',
  'Europe/Gibraltar',
  'America/Godthab',
  'America/Danmarkshavn',
  'America/Scoresbysund',
  'America/Thule',
  'Europe/Athens',
  'Atlantic/South_Georgia',
  'America/Guatemala',
  'Pacific/Guam',
  'Africa/Bissau',
  'America/Guyana',
  'Asia/Hong_Kong',
  'America/Tegucigalpa',
  'America/Port-au-Prince',
  'Europe/Budapest',
  'Asia/Jakarta',
  'Asia/Pontianak',
  'Asia/Makassar',
  'Asia/Jayapura',
  'Europe/Dublin',
  'Asia/Jerusalem',
  'Asia/Kolkata',
  'Indian/Chagos',
  'Asia/Baghdad',
  'Asia/Tehran',
  'Atlantic/Reykjavik',
  'Europe/Rome',
  'America/Jamaica',
  'Asia/Amman',
  'Asia/Tokyo',
  'Africa/Nairobi',
  'Asia/Bishkek',
  'Pacific/Tarawa',
  'Pacific/Enderbury',
  'Pacific/Kiritimati',
  'Asia/Pyongyang',
  'Asia/Seoul',
  'Asia/Almaty',
  'Asia/Qyzylorda',
  'Asia/Qostanay', // https://bugs.chromium.org/p/chromium/issues/detail?id=928068
  'Asia/Aqtobe',
  'Asia/Aqtau',
  'Asia/Atyrau',
  'Asia/Oral',
  'Asia/Beirut',
  'Asia/Colombo',
  'Africa/Monrovia',
  'Europe/Vilnius',
  'Europe/Luxembourg',
  'Europe/Riga',
  'Africa/Tripoli',
  'Africa/Casablanca',
  'Europe/Monaco',
  'Europe/Chisinau',
  'Pacific/Majuro',
  'Pacific/Kwajalein',
  'Asia/Yangon',
  'Asia/Ulaanbaatar',
  'Asia/Hovd',
  'Asia/Choibalsan',
  'Asia/Macau',
  'America/Martinique',
  'Europe/Malta',
  'Indian/Mauritius',
  'Indian/Maldives',
  'America/Mexico_City',
  'America/Cancun',
  'America/Merida',
  'America/Monterrey',
  'America/Matamoros',
  'America/Mazatlan',
  'America/Chihuahua',
  'America/Ojinaga',
  'America/Hermosillo',
  'America/Tijuana',
  'America/Bahia_Banderas',
  'Asia/Kuala_Lumpur',
  'Asia/Kuching',
  'Africa/Maputo',
  'Africa/Windhoek',
  'Pacific/Noumea',
  'Pacific/Norfolk',
  'Africa/Lagos',
  'America/Managua',
  'Europe/Amsterdam',
  'Europe/Oslo',
  'Asia/Kathmandu',
  'Pacific/Nauru',
  'Pacific/Niue',
  'Pacific/Auckland',
  'Pacific/Chatham',
  'America/Panama',
  'America/Lima',
  'Pacific/Tahiti',
  'Pacific/Marquesas',
  'Pacific/Gambier',
  'Pacific/Port_Moresby',
  'Pacific/Bougainville',
  'Asia/Manila',
  'Asia/Karachi',
  'Europe/Warsaw',
  'America/Miquelon',
  'Pacific/Pitcairn',
  'America/Puerto_Rico',
  'Asia/Gaza',
  'Asia/Hebron',
  'Europe/Lisbon',
  'Atlantic/Madeira',
  'Atlantic/Azores',
  'Pacific/Palau',
  'America/Asuncion',
  'Asia/Qatar',
  'Indian/Reunion',
  'Europe/Bucharest',
  'Europe/Belgrade',
  'Europe/Kaliningrad',
  'Europe/Moscow',
  'Europe/Simferopol',
  'Europe/Kirov',
  'Europe/Astrakhan',
  'Europe/Volgograd',
  'Europe/Saratov',
  'Europe/Ulyanovsk',
  'Europe/Samara',
  'Asia/Yekaterinburg',
  'Asia/Omsk',
  'Asia/Novosibirsk',
  'Asia/Barnaul',
  'Asia/Tomsk',
  'Asia/Novokuznetsk',
  'Asia/Krasnoyarsk',
  'Asia/Irkutsk',
  'Asia/Chita',
  'Asia/Yakutsk',
  'Asia/Khandyga',
  'Asia/Vladivostok',
  'Asia/Ust-Nera',
  'Asia/Magadan',
  'Asia/Sakhalin',
  'Asia/Srednekolymsk',
  'Asia/Kamchatka',
  'Asia/Anadyr',
  'Asia/Riyadh',
  'Pacific/Guadalcanal',
  'Indian/Mahe',
  'Africa/Khartoum',
  'Europe/Stockholm',
  'Asia/Singapore',
  'America/Paramaribo',
  'Africa/Juba',
  'Africa/Sao_Tome',
  'America/El_Salvador',
  'Asia/Damascus',
  'America/Grand_Turk',
  'Africa/Ndjamena',
  'Indian/Kerguelen',
  'Asia/Bangkok',
  'Asia/Dushanbe',
  'Pacific/Fakaofo',
  'Asia/Dili',
  'Asia/Ashgabat',
  'Africa/Tunis',
  'Pacific/Tongatapu',
  'Europe/Istanbul',
  'America/Port_of_Spain',
  'Pacific/Funafuti',
  'Asia/Taipei',
  'Europe/Kiev',
  'Europe/Uzhgorod',
  'Europe/Zaporozhye',
  'Pacific/Wake',
  'America/New_York',
  'America/Detroit',
  'America/Kentucky/Louisville',
  'America/Kentucky/Monticello',
  'America/Indiana/Indianapolis',
  'America/Indiana/Vincennes',
  'America/Indiana/Winamac',
  'America/Indiana/Marengo',
  'America/Indiana/Petersburg',
  'America/Indiana/Vevay',
  'America/Chicago',
  'America/Indiana/Tell_City',
  'America/Indiana/Knox',
  'America/Menominee',
  'America/North_Dakota/Center',
  'America/North_Dakota/New_Salem',
  'America/North_Dakota/Beulah',
  'America/Denver',
  'America/Boise',
  'America/Phoenix',
  'America/Los_Angeles',
  'America/Anchorage',
  'America/Juneau',
  'America/Sitka',
  'America/Metlakatla',
  'America/Yakutat',
  'America/Nome',
  'America/Adak',
  'Pacific/Honolulu',
  'America/Montevideo',
  'Asia/Samarkand',
  'Asia/Tashkent',
  'America/Caracas',
  'Asia/Ho_Chi_Minh',
  'Pacific/Efate',
  'Pacific/Wallis',
  'Pacific/Apia',
  'Africa/Johannesburg',
];

export const months = [
  {
    name: 'January',
    short: 'JAN',
    short2: 'Jan',
    number: 1,
    days: 31,
  },
  {
    name: 'February',
    short: 'FEB',
    short2: 'Feb',
    number: 2,
    days: 28,
  },
  {
    name: 'March',
    short: 'MAR',
    short2: 'Mar',
    number: 3,
    days: 31,
  },
  {
    name: 'April',
    short: 'APR',
    short2: 'Apr',
    number: 4,
    days: 30,
  },
  {
    name: 'May',
    short: 'MAY',
    short2: 'Mary',
    number: 5,
    days: 31,
  },
  {
    name: 'June',
    short: 'JUN',
    short2: 'Jun',
    number: 6,
    days: 30,
  },
  {
    name: 'July',
    short: 'JUL',
    short2: 'Jul',
    number: 7,
    days: 31,
  },
  {
    name: 'August',
    short: 'AUG',
    short2: 'Aug',
    number: 8,
    days: 31,
  },
  {
    name: 'September',
    short: 'SEP',
    short2: 'Sep',
    number: 9,
    days: 30,
  },
  {
    name: 'October',
    short: 'OCT',
    short2: 'Oct',
    number: 10,
    days: 31,
  },
  {
    name: 'November',
    short: 'NOV',
    short2: 'Nov',
    number: 11,
    days: 30,
  },
  {
    name: 'December',
    short: 'DEC',
    short2: 'Dec',
    number: 12,
    days: 31,
  },
];
