export const STRINGS = {
  DATE_FORMATES: {
    DD_MM_YYYY: 'DD/MM/YYYY',
    YYYY_MM_DD: 'YYYY-MM-DD',
    YYYY_MM_DD_HH_MM_A: 'YYYY-MM-DD hh:mm A',
  },
  GENERIC: {
    SOMETHING_WENT_WRONG: 'Something went wrong',
    N_A: 'N/A',
    STATUS: 'Status',
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
  },
  KEY_VALUES: {},
  // TRANSACTIONS SCREEN
  TRANSACTION: {
    showing: 'Showing',
    of: 'of',
    filteredBy: 'Filtered By:',
    all: 'All',
    noTransactionsFound: 'No Transactions Found',
  },

  // TRANSACTION FILTER SCREEN
  TRANSACTION_FILTER: {
    filter: 'Filter',
    transactionMode: 'Transaction Mode',
    clear: 'Clear',
    filterButton: 'Filter',
    all: 'All',
    sandBox: 'Sand Box',
    live: 'Live',
  },

  // TRANSACTION VIEW COMPONENT
  TRANSACTION_VIEW: {
    succeeded: 'succeeded',
    programAmount: 'Program Amount',
    transaction: 'Transaction',
    salePage: 'Sale Page',
    commissionAmount: 'Commission Amount',
    transactionMode: 'Transaction Mode',
    agreementPDF: 'Agreement PDF',
    marketingAffiliateCommission: 'Marketing Affiliate Commission',
    date: 'Date',
    preview: 'Preview',
  },

  // COMMISSION SCREEN
  COMMISSION: {
    title: 'Commission Detail',
    totalCommission: 'Total Commission',
    paidCommission: 'Paid Commission',
    pendingCommission: 'Pending Commission',
    noTransactionsFound: 'No Transactions Found',
  },

  // COMMISSION TRANSACTION VIEW COMPONENT
  COMMISSION_TRANSACTION_VIEW: {
    transactionDate: 'Transaction Date',
    credit: 'Credit',
    paid: 'Paid',
  },

  // PAYMENT REQUEST SCREEN
  PAYMENT_REQUEST: {
    showing: 'Showing',
    of: 'of',
    noPaymentRequestsFound: 'No Payment Requests Found',
    deleteConfirmation: 'Are you sure you want to delete this payment request?',
    cancelConfirmation: 'Are you sure you want to cancel this payment request?',
    // Options
    edit: 'Edit',
    delete: 'Delete',
    viewDetail: 'View Detail',
    agreementConfiguration: 'Agreement Configuration',
    manageProgrammeAccess: 'Manage Programme Access',
    manageProgressAccess: 'Manage Progress Access',
    copyBankPaymentLink: 'Copy Bank Payment Link',
    markRequestAsCancelled: 'Mark Request As Cancelled',
    markRequestAsPaid: 'Mark Request As Paid',
    // Sort options
    all: 'All',
    pending: 'Pending',
    paid: 'Paid',
    processing: 'Processing',
    cancelled: 'Cancelled',
  },

  // PAYMENT REQUEST DETAIL SCREEN
  PAYMENT_REQUEST_DETAIL: {
    title: 'Payment Request Transaction',
    enterCardDetails: 'Enter Card Details',
    cardNumberPlaceholder: 'Card Number...',
    pay: 'Pay',
    successful: 'Successful',
    failed: 'Failed',
    reminder: 'Reminder',
    email: 'Email',
    notification: 'Notification',
    message: 'Message',
    whatsapp: 'Whatsapp',
    sendReminder: 'Send Reminder',
    sendReminderConfirmation: 'Are you sure you want to send reminder ?',
    transactions: 'Transactions',
    requestType: 'Request Type',
    totalAmount: 'Total Amount:',
    initialDepositAmount: 'Initial Deposit Amount:',
    totalInstallments: 'Total Installments:',
    installmentsPlan: 'Installments Plan:',
    amount: 'Amount:',
    transactionNote: 'Transaction Note:',
    transactionDate: 'Transaction Date:',
    status: 'Status:',
    paymentSuccessful: 'Payment Successful',
    paymentFailed: 'Payment Failed',
    failed: 'Failed',
    reminderSentSuccess: 'Reminder sent successfully',
  },

  // BANK OPTION MODAL
  BANK_OPTION_MODAL: {
    title: 'Payment Request Detail',
    name: 'Name',
    email: 'Email',
    paymentInEuro: 'Payment in Euro',
    paymentInPound: 'Payment in Pound',
    copyBankUrl: 'Copy Bank Url',
    bankUrlCopied: 'Bank URL coppied to clipboard',
  },

  // MANAGE PROGRAMME ACCESS SCREEN
  MANAGE_PROGRAMME_ACCESS: {
    title: 'Manage Programme Access',
    selectAll: 'Select All',
    update: 'Update',
    updateSuccess: 'Programme Access Updated Successfully',
    somethingWentWrong: 'Something went wrong',
    programmeTitle: 'Programme Title',
    noOfStartDays: 'No of Start Days',
    noOfEndDays: 'No of End Days',
  },

  // PAYMENT REQUEST VIEW COMPONENT
  REQUEST_VIEW: {
    requestTitle: 'Request Title',
    product: 'Product',
    paymentTemplate: 'Payment Template',
    requestType: 'Request Type',
    totalAmount: 'Total Amount',
    initialAmount: 'Initial Amount',
    installmentAmount: 'Installment Amount',
    month: 'Month',
    salePage: 'Sale Page',
    considerPurchasingUser: 'Consider Purchasing User',
    leadStatus: 'Lead Status',
    firstPaid: 'First Paid',
    status: 'Status',
    paidOn: 'PAID on',
    cancelledOn: 'Cancelled on',
    processing: 'PROCESSING',
    pending: 'PENDING',
    active: 'ACTIVE',
    inactive: 'INACTIVE',
  },

  // ASSESSMENT LIST SCREEN
  ASSESSMENT_LIST: {
    attitudeCoins: 'Attitude Coins',
    delegate: 'Delegate',
    nurture: 'Nurture',
    completedDate: 'Completed Date',
    assessmentLevel: 'Assessment Level',
    showing: 'Showing',
    of: 'of',
    viewHistory: 'View History',
  },

  // ASSESSMENT DETAIL SCREEN
  ASSESSMENT_DETAIL: {
    assessmentHistory: 'Assessment History',
    completedDate: 'Completed Date: ',
    clientNotes: 'Client Notes',
    thoughts: 'THOUGHTS',
    feelings: 'FEELINGS',
    actions: 'ACTIONS',
  },

  // ASSESSMENT NOTES LIST SCREEN
  ASSESSMENT_NOTES_LIST: {
    title: 'Notes',
    noNotes: 'No notes',
    edit: 'Edit',
    delete: 'Delete',
    deleteConfirmation: 'Are you sure you want to delete this note?',
  },

  // ASSESSMENT NOTES ADD/EDIT SCREEN
  ASSESSMENT_NOTES_ADD_EDIT: {
    editNote: 'Edit Note',
    addNote: 'Add Note',
    cancel: 'Cancel',
    update: 'Update',
    save: 'Save',
    pleaseEnterNote: 'Please enter note',
  },

  // LOGIN SCREEN
  LOGIN: {
    welcomeTo: 'Welcome To',
    enterDetails: 'Enter your details below.',
    emailLabel: 'Email Address*',
    passwordLabel: 'Password*',
    forgotPassword: 'Forgot Password?',
    loginButton: 'LOGIN',
    enterEmail: 'Please enter your email',
    enterValidEmail: 'Please enter valid email',
    enterPassword: 'Please enter password',
    loginError: 'Login Error',
    tryAgain: 'Please try again',
  },

  // ADD PAYMENT REQUEST SCREEN
  ADD_PAYMENT_REQUEST: {
    addPaymentRequest: 'Add Payment Request',
    editPaymentRequest: 'Edit Payment Request',
    copyBankDetails: 'Copy Bank Details',
    alert: 'Alert',
    pleaseSelectCountry: 'Please select country',
    memberInfo: 'Member Info',
    existingMember: 'Existing Member',
    newMember: 'New Member',
    members: 'Members*',
    firstName: 'First Name*',
    lastName: 'Last Name*',
    email: 'Email*',
    chooseCountry: 'Choose a country',
    noCountrySelected: 'No Country Selected...',
    clear: 'Clear',
    paymentRequestInfo: 'Payment Request Info',
    paymentTemplate: 'Payment Template',
    requestTitle: 'Request Title*',
    status: 'Status',
    currency: 'Currency*',
    product: 'Product*',
    programme: 'Programme',
    paymentRequestType: 'Payment Request Type',
    totalAmount: 'Total Amount*',
    initialAmount: 'Initial Amount*',
    noOfInstallments: 'No. of Installments*',
    installmentsAmount: 'Installments Amount*',
    planPaymentType: 'Plan Payment Type*',
    noOfDays: 'No. of Days*',
    vatNumber: 'VAT Number',
    leadStatus: 'Lead Status',
    considerPurchasingUserAs: 'Consider Purchasing User As*',
    sourceMember: ' Source Member',
    salePages: 'Sale Pages',
    transactionNote: 'Transaction Note',
    submit: 'Submit',
    member: 'Member',
    active: 'Active',
    inactive: 'Inactive',
    dollar: 'Dollar',
    ukPounds: 'UK Pounds',
    euro: 'Euro',
    onetime: 'Onetime',
    recurring: 'Recurring',
    monthly: 'Monthly',
    weekly: 'Weekly',
    yearly: 'Yearly',
    custom: 'Custom',
  },
};
